<a href="https://colab.research.google.com/github/ittiwarianiket2526-hash/Data-Structure-/blob/main/PDS%20Prac%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name - Aniket Tiwari     |    
Roll No. - 42                                                      |
Class - SYIT                                                        |
Batch - 00                                           |
Date Of Assignment - 05-08-2026                       |
Date Of Submission - 05-08-2026                      

Practical 4   -   Numpy

In [6]:
import numpy as np

**a. Write a python code to create Numpy Array.**

In [9]:
a = np.array([1,2,3])
print(a)

[1 2 3]


**b. Write a python code to demonstrate basic operations on single array.**

In [8]:
a + 10
a * 2

array([2, 4, 6])

**c. Write a python code to create array with 10 elements and slice element from 1st to 5th element.**

In [12]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
b[0:5]

array([1, 2, 3, 4, 5])

**d. Write a python code to sort an array alphabetically.**

In [13]:
c = np.array(["Aniket","Raj","Jay","Amit"])
np.sort(c)

array(['Amit', 'Aniket', 'Jay', 'Raj'], dtype='<U6')

**e. Write a python code to create a filter array that will return maximum values from an array.**

In [14]:
price = np.array([2000,4000,8934,84256,85854])
price[price > 50000]

array([84256, 85854])